# Lista 6 - Métodos computacionais para economistas

Lista de exercícios para praticar funções dos pacotes Python estudados em aula, Numpy, SciPy e Pandas.

**Lista de exercícios para praticar funções dos pacotes Python estudados em aula.**

Monitor: Nikolas Schiozer

E-mail: nikolas.s@usp.br

***Exercícios Numpy***

**Exercício 1**

Abaixo temos uma matriz A,B e C. Realize as seguintes operações:
* Some a matriz A com B com o método "add"
* Multiplique o resultado do item anterior por C com o método "dot"
* Verifique se a matriz anterior possui determinante diferente de 0 usando método visto em aula
* Se o determinante for diferente de 0, calcule a matriz inversa obtida pelo item anterior usando método visto em aula

In [119]:
# Supondo as matrizes A, B e C:
A = [[1,2],[3,4]]
B = [[4,5],[6,7]]
C = [[1.2,0.8],[0.2,1]]

import numpy as np

print("Print")
print(A)
print("Print")
print(B)
print("Print")
print(C)
  
# Soma
print("Soma de duas matrizes")
print(np.add(A, B))

# Soma
D = np.add(A, B)

# Produto
E = np.dot( C , D )

# Cálculo do determinante
print(np.linalg.det(E))

# Cálculo da inversa
print(np.linalg.inv(E))

Print
[[1, 2], [3, 4]]
Print
[[4, 5], [6, 7]]
Print
[[1.2, 0.8], [0.2, 1]]
Soma de duas matrizes
[[ 5  7]
 [ 9 11]]
-8.320000000000023
[[-1.49038462  2.06730769]
 [ 1.20192308 -1.58653846]]


**Exercício 2**

Obtenha os números das linhas de uma matriz numpy que têm pelo menos um item maior do que um valor especificado X. Para fazer o exercício, use as funções numpy.where() e numpy.any() juntas.

In [120]:
# Importando:
import numpy
  
# Matriz
arr = numpy.array([[1, 2, 3, 4, 5],
                  [10, -3, 30, 4, 5],
                  [3, 2, 5, -4, 5],
                  [9, 7, 3, 6, 5] 
                 ])
  
# Valor:
X = 6
  
print("Dada a matriz:\n", arr)
  
# Descobrindo o número de linhas
print(numpy.any(arr > X,axis = 1))

bool = numpy.any( arr > X ,axis = 1)

print(bool)

output  = numpy.where(bool)
  
# Output
print("Result:\n", output)

Dada a matriz:
 [[ 1  2  3  4  5]
 [10 -3 30  4  5]
 [ 3  2  5 -4  5]
 [ 9  7  3  6  5]]
[False  True False  True]
[False  True False  True]
Result:
 (array([1, 3], dtype=int64),)


**Exercício 3**

numpy.matlib.rand() e numpy.matlib.randn() são outras funções para fazer operações matriciais em numpy. Elas retornam uma matriz de valores aleatórios de uma distribuição uniforme sobre [0, 1] e normal com determinada forma. Abaixo obtenha uma matriz 3 x 4 com valores aleatórios obtidos de uma distribuição uniforme e uma matriz 10 x 10 com valores obtidos de uma distribuição normal.

In [121]:
# Importanto
import numpy as np
  
# 3 x 4 matriz aleatória
out_mat = np.matlib.rand((3, 4)) 
print ("Output matrix : ", out_mat) 

  
# 2 x 2 matriz normal aleatória
out_mat = np.matlib.randn((2, 2)) 
print ("Output matrix : ", out_mat) 

Output matrix :  [[0.64264149 0.94302788 0.4643252  0.78483527]
 [0.42606626 0.81209981 0.35746885 0.10402751]
 [0.76546789 0.16099132 0.41663398 0.76861491]]
Output matrix :  [[-0.53953912 -2.28088393]
 [-0.01215529 -0.69161644]]


***Exercícios SciPy***

**Exercício 1**

Integre a função $x^2 + x + 2$ utilizando a função "quad" da biblioteca "Scipy", definida no intervalo de $[0,100]$.

In [122]:
from scipy.integrate import quad

def eqn(x):
  return x**2 + x + 2

result = quad(eqn,0,100)
print(result)

# O primeiro valor da tupla resultante da função quad é o valor da integral avaliada no intervalo passado como argumento. 
# O segundo elemento da tupla representa o erro calculado pelo algoritmo no cálculo da integral.

(338533.3333333333, 3.758475012697696e-09)


**Exercício 2**

Minimize a equação $x^2 + 30x - 100$ utilizando a função "minimize" da biblioteca "Scipy", utilizando o algortimo 'BFGS'. Dê como resposta um print do valor encontrado.

In [123]:
from scipy.optimize import minimize

def eqn(x):
  return x**2 + 30*x - 100

mymin = minimize(eqn, x0=0, method="BFGS")

print(mymin.x)

[-14.99999943]


***Exercícios Pandas***

**Exercício 1**

Abaixo temos 4 listas com algunas informações sobre as partidas da Copa do Mundo até o dia 23/11. Temos o nome das seleções que já fizera sua primeira partida, a que continente pertence o respectivo país, número de vitórias, pontos ganhos e saldo de gols. Junte as cinco em um data.frame do Pandas.

In [124]:
Times = ['Argentina','Australia','Belgium','Canada','Costa Rica','Croatia','Denmark','Ecuador','England','France','Germany','Iran','Japan','Mexico','Morocco','Netherlands','Poland','Qatar','Saudi Arabia','Senegal','Spain','Tunisia','United States','Wales']
Continente = ['Am.Sul','Oceania','Europa','Am.Norte','Am.Norte','Europa','Europa','Am.Sul','Europa','Europa','Europa','Asia','Asia','Am.Norte','Africa','Europa','Europa','Asia','Asia','Africa','Europa','Africa','Am.Norte','Europa']
V = [0,0,1,0,0,0,0,1,1,1,0,0,1,0,0,1,0,0,1,0,1,0,0,0]
Pts = [0,0,3,0,0,1,1,3,3,3,0,0,3,1,1,3,1,0,3,0,3,1,1,1]
SD = [-1,-3,1,-1,-7,0,0,2,4,3,-1,-4,1,0,0,2,0,-2,1,-2,7,0,0,0]

import pandas as pd

# Séries a partir de listas
Times_series = pd.Series(Times)
Continente_series = pd.Series(Continente)
V_series = pd.Series(V)
Pts_series = pd.Series(Pts)
SD_series = pd.Series(SD)


# Dicionário a partir de listas
frame = { 'Times': Times_series, 'Continente': Continente_series, 'V': V_series , 'Pts': Pts_series , 'SD': SD_series }

# Data.frame a partir de um dicionário
frame_WC = pd.DataFrame(frame)

# Print
frame_WC


Times Continente  V  Pts  SD
0       Argentina     Am.Sul  0    0  -1
1       Australia    Oceania  0    0  -3
2         Belgium     Europa  1    3   1
3          Canada   Am.Norte  0    0  -1
4      Costa Rica   Am.Norte  0    0  -7
5         Croatia     Europa  0    1   0
6         Denmark     Europa  0    1   0
7         Ecuador     Am.Sul  1    3   2
8         England     Europa  1    3   4
9          France     Europa  1    3   3
10        Germany     Europa  0    0  -1
11           Iran       Asia  0    0  -4
12          Japan       Asia  1    3   1
13         Mexico   Am.Norte  0    1   0
14        Morocco     Africa  0    1   0
15    Netherlands     Europa  1    3   2
16         Poland     Europa  0    1   0
17          Qatar       Asia  0    0  -2
18   Saudi Arabia       Asia  1    3   1
19        Senegal     Africa  0    0  -2
20          Spain     Europa  1    3   7
21        Tunisia     Africa  0    1   0
22  United States   Am.Norte  0    1   0
23          Wales     Europa  0    1   0

**Exercício 2**

Vamos realizar algumas mudanças no nosso data.frame.

* Substitua o título das colunas para "Seleções", "Continente", "Vitórias", "Pontos" e "SdG".
* Na primeira coluna, deixe todos os caracteres maiúsculos. Na segunda, minúsculos. 
* Crie uma nova coluna, chamada Soma, que é o resultado da soma dos valores das colunas vitórias, pontos e saldo de gols. 
* Crie uma nova coluna em que, se o valor de Soma estiver no quartil inferior, na coluna temos um booleano TRUE. Caso contrário, FALSE.

In [125]:
# Substituir os títulos
frame_WC.columns = ["Seleções", "Continente", "Vitórias", "Pontos" ,"SdG"]
#print(frame_WC.head())

# Mudança do texto. Primeira letra das palavras
frame_WC['Seleções'] = frame_WC['Seleções'].str.upper()

frame_WC['Continente'] = frame_WC['Continente'].str.lower()

#print(frame_WC.head())

# Operações com as colunas - criação de uma nova
frame_WC['Soma'] = frame_WC['Vitórias'] + frame_WC['Pontos'] + frame_WC['SdG']

print(frame_WC['Soma'].head())

#print(frame_WC['Soma'].describe())

# Operações booleanas com colunas
frame_WC['If'] = [ True if elem <= -1 else False for elem in frame_WC['Soma']]

frame_WC.head()



0   -1
1   -3
2    5
3   -1
4   -7
Name: Soma, dtype: int64


Seleções Continente  Vitórias  Pontos  SdG  Soma     If
0   ARGENTINA     am.sul         0       0   -1    -1   True
1   AUSTRALIA    oceania         0       0   -3    -3   True
2     BELGIUM     europa         1       3    1     5  False
3      CANADA   am.norte         0       0   -1    -1   True
4  COSTA RICA   am.norte         0       0   -7    -7   True

**Exercício 3**

A que continente pertencem os 5 países que apresentam o maior saldo de gols (SD) até o dia 23/11? Crie um novo data.frame que contenha apenas as linhas com estes 5 países e as colunas com nomes "Seleções","Vitórias" e Pontos". 

In [133]:
# Sorting na ordem desejada

fram2 = frame_WC.sort_values(by=['SdG'], ascending=False)

print(fram2)

# Criação de novo dataframe

fram3 = fram2[['Seleções','Vitórias','Pontos']]
fram4 = fram3[1:6]


# Utilizando .iloc para selecionar o número de colunas desejadas
fram5 = fram2.iloc[1:6,[0,2,3]]


print(fram5.head())
print(fram4.head())

         Seleções Continente  Vitórias  Pontos  SdG  Soma     If
20          SPAIN     europa         1       3    7    11  False
8         ENGLAND     europa         1       3    4     8  False
9          FRANCE     europa         1       3    3     7  False
7         ECUADOR     am.sul         1       3    2     6  False
15    NETHERLANDS     europa         1       3    2     6  False
12          JAPAN       asia         1       3    1     5  False
2         BELGIUM     europa         1       3    1     5  False
18   SAUDI ARABIA       asia         1       3    1     5  False
13         MEXICO   am.norte         0       1    0     1  False
22  UNITED STATES   am.norte         0       1    0     1  False
21        TUNISIA     africa         0       1    0     1  False
16         POLAND     europa         0       1    0     1  False
14        MOROCCO     africa         0       1    0     1  False
23          WALES     europa         0       1    0     1  False
6         DENMARK     eur